version: '3.9'

services:
  nginx:
    image: nginx
    container_name: v3_stbcms_nginx
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./nginx-conf:/etc/nginx/templates:ro
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare
      # - /etc/letsencrypt:/etc/letsencrypt
      # - /var/lib/letsencrypt:/var/lib/letsencrypt
      # - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443
  wagtail:
    image: ${WAGTAIL_IMAGE}
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 8000:8000
  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
