version: '3.9'

services:
  db:
    container_name: stbdb
    restart: unless-stopped
    image: postgres
    volumes:
      - ./dev-database/data:/var/lib/postgresql/data
      - ./dev-database/backup/:/tmp/backup
      - ./dev-database/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5434:5432

