version: '3.9'

services:
  nginx:
    image: nginx
    container_name: v3_stbcms_nginx
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./nginx-conf/nginx.cloudflare.conf.template:/etc/nginx/templates/nginx.cloudflare.conf.template:ro
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare
    ports:
      - 80:80
      - 443:443
  wagtail:
    image: ${WAGTAIL_IMAGE}
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 8000:8000
