version: '3.9'

services:
  db_stage:
    container_name: stbdb_stage
    restart: unless-stopped
    image: postgres
    volumes:
      - stage_db_data:/var/lib/postgresql/data
      - ./dev-database/stage-backup/:/tmp/backup
      - ./dev-database/init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env.stage
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5435:5432
  web_stage:
    image: stbcms:22.09.26.8
    ports:
      - 8000:8000
    env_file:
      - .env.stage

volumes:
  stage_db_data:
