# Generated by Django 4.1.1 on 2022-09-25 20:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('useful_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Date Updated')),
                ('ts_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date Created')),
                ('link_url', models.URLField(unique=True)),
                ('link_text', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulLinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulLinkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='useful_links.usefullink')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsefulLinkCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_items', to='useful_links.usefullink')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_useful_links', to='useful_links.usefullinkcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usefullink',
            name='categories',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='useful_links.UsefulLinkCategories', to='useful_links.UsefulLinkCategory', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='useful_links.UsefulLinkTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
