# Generated by Django 4.1.1 on 2022-09-25 21:06

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0002_usefullink_usefullinkcategory_usefullinktag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'verbose_name': 'Useful Link', 'verbose_name_plural': 'Useful Links'},
        ),
        migrations.AlterModelOptions(
            name='usefullinkcategory',
            options={'verbose_name': 'Useful Link Category', 'verbose_name_plural': 'Useful Link Categories'},
        ),
        migrations.AlterField(
            model_name='usefullinkcategory',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
