# Generated by Django 4.1.1 on 2022-10-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('useful_links', '0004_usefullink_is_live'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsefulLinksPage',
            new_name='UsefulLinkListingPage',
        ),
    ]
