# Generated by Django 4.1.1 on 2022-10-14 01:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('wagtailcore', '0076_modellogentry_revision'),
        ('useful_links', '0005_rename_usefullinkspage_usefullinklistingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('ts_updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Date Updated')),
                ('ts_created', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Date Created')),
                ('link_url', models.URLField(unique=True)),
                ('link_text', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('is_live', models.BooleanField(default=False, help_text='This link will not appear to site visitors unless this box is checked')),
                ('categories', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='useful_links.UsefulLinkCategories', to='useful_links.UsefulLinkCategory', verbose_name='Tags')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='useful_links.UsefulLinkTag', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
