# Generated by Django 4.1.1 on 2022-10-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0007_alter_usefullinkcategories_content_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefullinkpage',
            name='link_text',
        ),
    ]
