# Generated by Django 4.1.1 on 2022-10-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0009_remove_usefullinkpage_is_live'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefullinkpage',
            old_name='tags',
            new_name='topics',
        ),
    ]
