# Generated by Django 4.1.1 on 2022-10-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0010_rename_tags_usefullinkpage_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefullinkpage',
            name='topics',
        ),
        migrations.DeleteModel(
            name='UsefulLinkTag',
        ),
    ]
