# Generated by Django 4.1.1 on 2022-10-27 20:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0011_remove_usefullinkpage_topics_delete_usefullinktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinkTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Useful Link Topic',
                'verbose_name_plural': 'Useful Link Topics',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='UsefulLinkTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_items', to='useful_links.usefullinkpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_useful_links', to='useful_links.usefullinktopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='usefullinkpage',
            name='topics',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='useful_links.UsefulLinkTopics', to='useful_links.UsefulLinkTopic', verbose_name='Tags'),
        ),
    ]
