# Generated by Django 4.1.1 on 2022-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0012_usefullinktopic_usefullinktopics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullinklistingpage',
            name='disable_tags',
            field=models.BooleanField(default=False, help_text='Check this box to hide UI elements that show useful link Categories or Topics'),
        ),
    ]
