# Generated by Django 4.1.1 on 2022-10-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0013_usefullinklistingpage_disable_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullinklistingpage',
            name='header_blurb',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
