# Generated by Django 4.1.1 on 2022-10-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0014_usefullinklistingpage_header_blurb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefullinklistingpage',
            old_name='header_blurb',
            new_name='header_text',
        ),
    ]
