# Generated by Django 4.1.1 on 2022-09-14 01:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menulinklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulinklistitem',
            name='parent',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menulinklist'),
            preserve_default=False,
        ),
    ]
