# Generated by Django 4.1.1 on 2022-09-14 01:52

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0076_modellogentry_revision'),
        ('menus', '0004_menulinklistitem_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=80)),
                ('external_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='MenuLinkList',
            new_name='MenuSection',
        ),
        migrations.DeleteModel(
            name='MenuLinkListItem',
        ),
        migrations.AddField(
            model_name='menusectionitem',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menusection'),
        ),
    ]
