# Generated by Django 4.1.1 on 2022-09-14 02:39

from django.db import migrations
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sections',
            field=wagtail.fields.StreamField([('section', wagtail.snippets.blocks.SnippetChooserBlock('menus.MenuSection'))], use_json_field=True),
        ),
    ]
