# Generated by Django 4.1.1 on 2022-09-17 17:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_rename_name_menu_title_rename_name_menusection_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='sections',
        ),
        migrations.AddField(
            model_name='menu',
            name='variant',
            field=wagtail.fields.StreamField([('footer', wagtail.blocks.StructBlock([('sections', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, null=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('_text', wagtail.blocks.CharBlock(label='Text', max_length=240, required=False)), ('_kind', wagtail.blocks.ChoiceBlock(choices=[('URL', 'URL'), ('PAGE', 'Page')], help_text='If you want to link to a page on some other website (e.g. twitter.com) chose "URL". If you want to link to a page on this site, choose "Page"', label='Kind')), ('_page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('_url', wagtail.blocks.URLBlock(label='URL', required=False))])))]))), ('include_social_media', wagtail.blocks.BooleanBlock())])), ('mobile_menu', wagtail.blocks.StructBlock([('brand', wagtail.blocks.CharBlock(max_length=32)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock())), ('call_to_action', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('_text', wagtail.blocks.CharBlock(label='Text', max_length=240, required=False)), ('_kind', wagtail.blocks.ChoiceBlock(choices=[('URL', 'URL'), ('PAGE', 'Page')], help_text='If you want to link to a page on some other website (e.g. twitter.com) chose "URL". If you want to link to a page on this site, choose "Page"', label='Kind')), ('_page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('_url', wagtail.blocks.URLBlock(label='URL', required=False))]), max_num=2)), ('include_social_media', wagtail.blocks.BooleanBlock())])), ('navbar', wagtail.blocks.StructBlock([('brand', wagtail.blocks.CharBlock(max_length=32)), ('pages', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock())), ('call_to_action', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('_text', wagtail.blocks.CharBlock(label='Text', max_length=240, required=False)), ('_kind', wagtail.blocks.ChoiceBlock(choices=[('URL', 'URL'), ('PAGE', 'Page')], help_text='If you want to link to a page on some other website (e.g. twitter.com) chose "URL". If you want to link to a page on this site, choose "Page"', label='Kind')), ('_page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('_url', wagtail.blocks.URLBlock(label='URL', required=False))]), max_num=2))]))], null=True, use_json_field=True),
        ),
    ]
