# Generated by Django 4.1.1 on 2022-09-12 20:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('image', wagtail.blocks.ChooserBlock())]))], blank=True, use_json_field=True),
        ),
    ]
