# Generated by Django 4.1.1 on 2022-09-13 21:52

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=140)), ('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link'])), ('link', wagtail.blocks.StructBlock([('kind', wagtail.blocks.ChoiceBlock(choices=[('page', 'Page'), ('url', 'URL')])), ('text', wagtail.blocks.CharBlock(max_length=240)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(required=False))], features=['link']))], label_format='Call To Action'))])), ('article', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link']))], blank=True, use_json_field=True),
        ),
    ]
