# Generated by Django 4.1.1 on 2022-09-16 05:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('cta', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=140)), ('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link'])), ('link', wagtail.blocks.StructBlock([('kind', wagtail.blocks.ChoiceBlock(choices=[('url', 'URL'), ('page', 'Page')], help_text='If you want to link to a page on some other website (e.g. twitter.com) chose "URL". If you want to link to a page on this site, choose "Page"')), ('text', wagtail.blocks.CharBlock(max_length=240)), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('url', wagtail.blocks.URLBlock(label='URL', required=False))]))], label='Call To Action'))])), ('article', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link']))], blank=True, use_json_field=True),
        ),
    ]
