# Generated by Django 4.1.1 on 2022-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='disable_scroll_prompt',
            field=models.BooleanField(default=False, help_text='Check this box to hide the bouncing arrow that appears below the hero section.'),
        ),
    ]
