# Generated by Django 4.1.1 on 2022-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
