# Generated by Django 4.1.1 on 2022-09-26 00:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostpage_ts_created_blogpostpage_ts_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='teaser',
            field=wagtail.fields.RichTextField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
