# Generated by Django 4.1.1 on 2022-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpostpage_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='teaser',
            field=models.TextField(max_length=240),
        ),
    ]
