# Generated by Django 4.1.1 on 2022-09-26 00:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpostpage_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock())], default=[], use_json_field=True),
            preserve_default=False,
        ),
    ]
