# Generated by Django 4.1.1 on 2022-09-26 03:26

from django.db import migrations, models
import uuid
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='uid_slug',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'link'])), ('photo', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.TextBlock(max_length=300, required=False))]))], use_json_field=True),
        ),
    ]
