# Generated by Django 4.1.1 on 2022-09-20 02:31

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='detail_description',
            field=wagtail.fields.RichTextField(default='', help_text='The description that will appear on the event detail page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='listing_description',
            field=models.TextField(default='', help_text='A description of the event that will appear on the event listing page.', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140)), ('time_override', wagtail.blocks.CharBlock(max_length=140))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140)), ('time_override', wagtail.blocks.CharBlock(max_length=140))]))], default=[], use_json_field=True),
            preserve_default=False,
        ),
    ]
