# Generated by Django 4.1.1 on 2022-09-21 01:43

from django.db import migrations, models
import django.utils.timezone
import uuid
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpage_detail_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_description',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='location_link',
            field=models.URLField(blank=True, help_text='If provided, this link will be embedded in the location description text'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='ts_created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='ts_updated',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='uid_slug',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('current', wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(max_length=140, required=False))]))])), ('previous', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(max_length=140, required=False))]))])))], blank=True, use_json_field=True),
        ),
    ]
