# Generated by Django 4.1.1 on 2022-09-21 01:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpage_location_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='include_contact_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('current', wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))]))], label='Currently scheduled for...')), ('previous', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))]))]), label='Previously scheduled for...'))], blank=True, use_json_field=True),
        ),
    ]
