# Generated by Django 4.1.1 on 2022-09-24 20:29

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventpage_include_contact_link_alter_eventpage_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='list_as_upcoming',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('current', wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))]))], label='Currently scheduled for...')), ('previous', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Date/Time Override', max_length=140, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False))]))], label='Previously scheduled date/time'), label='Previously scheduled for...'))], blank=True, use_json_field=True),
        ),
    ]
