# Generated by Django 4.1.1 on 2022-10-08 19:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventpage_list_as_upcoming_alter_eventpage_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('current', wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Custom Date/Time Message', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Custom Date/Time Message', max_length=140, required=False))]))], label='Currently scheduled for...')), ('previous', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Custom Date/Time Message', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(label='Custom Date/Time Message', max_length=140, required=False))]))], label='Previously scheduled date/time'), label='Previously scheduled for...'))], blank=True, use_json_field=True),
        ),
    ]
