# Generated by Django 4.1.1 on 2022-10-08 20:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventpage_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='when',
            field=wagtail.fields.StreamField([('current', wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(help_text="Leave the 'Date/Time' field blank and enter a custom message here if you want more flexibility in how you describe when an event starts. Use the preview to verify the event will display in the way you expect.", label='Custom Date/Time Message', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(help_text="Leave the 'Date/Time' field blank and enter a custom message here if you want more flexibility in how you describe when an event starts. Use the preview to verify the event will display in the way you expect.", label='Custom Date/Time Message', max_length=140, required=False))]))], label='Currently scheduled for...')), ('previous', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('start', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(help_text="Leave the 'Date/Time' field blank and enter a custom message here if you want more flexibility in how you describe when an event starts. Use the preview to verify the event will display in the way you expect.", label='Custom Date/Time Message', max_length=140, required=False))])), ('end', wagtail.blocks.StructBlock([('date_time', wagtail.blocks.DateTimeBlock(blank=True, label='Date/Time', null=True, required=False)), ('time_override', wagtail.blocks.CharBlock(label='Time Override', max_length=140, required=False)), ('date_time_override', wagtail.blocks.CharBlock(help_text="Leave the 'Date/Time' field blank and enter a custom message here if you want more flexibility in how you describe when an event starts. Use the preview to verify the event will display in the way you expect.", label='Custom Date/Time Message', max_length=140, required=False))]))], label='Previously scheduled date/time'), label='Previously scheduled for...'))], blank=True, use_json_field=True),
        ),
    ]
